# Enable CSRF protection for forms
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        # Enable stateless CSRF protection for forms and logins/logouts
        stateless_token_ids:
            - submit
            - authenticate
            - logout
