vich_uploader:
  db_driver: orm

  mappings:
    document_file:
      uri_prefix: /uploads/documents
      upload_destination: '%kernel.project_dir%/var/uploads/documents'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer